<template>
    <main>
    <h1>Toi Ohomai Regulations</h1>
    <br>

    <p>The Regulatory Framework for Quality Assurance document encompasses the institution's Academic Statute, Academic Regulations, Quality Management System and staff and student Codes of Conduct.</p>
    <br><p><b>2018 Documents</b></p>
      <a href="https://toiohomai.ac.nz/sites/default/files/inline-files/2018%20Regulatory%20Framework%20%28approved%20AB121017%29.pdf">2018 Toi Ohomai Institute of Technology Regulatory Framework for Quality Assurance (pdf, 580kb)</a><br>
      <a href="https://toiohomai.ac.nz/sites/default/files/inline-files/Toi%20Ohomai_Enrolment%20Terms%20and%20Conditions_2018.pdf">2018 Toi Ohomai Institute of Technology Student Terms and Conditions of Enrolment (pdf, 41kb)</a><br>
      <a href="https://toiohomai.ac.nz/sites/default/files/inline-files/Student%20Code%20of%20Conduct%20from%202018%20Regs.pdf">Student Code of Conduct* (pdf, 83kb)</a>
    <br>
    <br>

    <p><b>ENTRY CRITERIA</b></p>
    <a href="https://toiohomai.ac.nz/sites/default/files/inline-files/Academic%20Entry%20and%20Admission%20from%202018%20Regs.pdf">Academic Entry and Admission* (pdf, 190kb)</a>
    <p>* excerpt from the 2018 Toi Ohomai Institute of Technology Regulatory Framework for Quality Assurance.</p>
    <br>

    <p><b>FEES</b></p>
    <p>Fee policies and other information can be found on our Fees information page.</p>
    <br>

    <p><b>QUALITY ASSURANCE STATUS</b></p>
    <p>Toi Ohomai Institute of Technology participated in its first External Evaluation and Review (EER) in May of 2018 and was rated Category 2. This is the highest rating achievable until the newly formed institution has more history behind it. The next review is due in 2022. Read the full report on the NZQA website.</p>
    <br>
    <p>All of Toi Ohomai Institute of Technology's programmes and courses are quality assured by the New Zealand Qualifications Authority (NZQA).</p>
    <br>

    <p><b>THE EDUCATION (PASTORAL CARE OF INTERNATIONAL STUDENTS) CODE OF PRACTICE</b></p>
    <p>Toi Ohomai Institute of Technology has agreed to observe and be bound by The Education (Pastoral Care of International Students) Code of Practice 2016, published by the Ministry of Education. Copies of the code are available on request from this institution or from the New Zealand Ministry of Education website.</p>
        </section>
    </main>
</template>

<script>
    export default {
        name: 'Policy',
        props: {
            name: "Policy"
        },
    }
</script>

<style lang="css" scoped>

</style>